Temporarily fix containerd version installation in Dockerfiles: https://github.com/nestybox/sysbox/issues/973

diff --git a/Dockerfile.systemd b/Dockerfile.systemd
--- a/Dockerfile.systemd
+++ b/Dockerfile.systemd
@@ -91,6 +91,17 @@ RUN curl --retry 5 --retry-max-time 40 \
     mkdir -p /usr/local/lib/docker/cli-plugins && \
     ln -s /usr/local/bin/docker-compose /usr/local/lib/docker/cli-plugins/docker-compose
 
+# TODO: Remove when this issue is fixed: https://github.com/nestybox/sysbox/issues/973
+# Temporarly fix containerd version
+RUN set -eux; \
+    . /etc/os-release; \
+    if [ -z "${VERSION_ID:-}" ] || [ -z "${VERSION_CODENAME:-}" ]; then \
+        echo "Unable to detect Ubuntu version metadata"; exit 1; \
+    fi; \
+    apt-get update; \
+    apt-get install -y --allow-downgrades "containerd.io=1.7.28-1~ubuntu.${VERSION_ID}~${VERSION_CODENAME}" && \
+    apt-mark hold containerd.io
+
 # Make use of stopsignal (instead of sigterm) to stop systemd containers.
 STOPSIGNAL SIGRTMIN+3
 
